export const siteConfig = {
  name: "Muhammad Sarib Khan portfolio",
  authorName: "Muhammad Sarib Khan",
  username: "saribkhan",
  description:
    "Muhammad Sarib Khan's Portfolio",
  url: "https://portfolio-ou3v.vercel.app",
  links: {
    github: "https://github.com/yurnero14",
  },
  ogImage: "/Sarib.jpg",
  iconIco: "/favicon.ico",
  logoIcon:"/logo.png",
  keywords: [
    "Muhammad Sarib Khan",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio",
    "React portfolio",
    "Developer portfolio",
    "Portfolio website",
    "Next.js",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio",
    "Web developer portfolio",
    "Responsive portfolio ",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase",
    "Career timeline",
    "Portfolio with dark mode",
    "GitHub portfolio",
    "AI Engineer",
    "AI application Engineer",
    "Data Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "Software Engineer",
    "Software Developer",
    "Frontend Developer",
    "Backend Developer"
  ],
};
